### ISSUE TITLE
warmup_linear- issue 

### ISSUE THREAD

**Issue by niranjan8129** [enod/mongolian-bert-ner#1]
Hi,

 I am not able to train the model . I am getting an error (warmup_linear - lib not available ) while taring the model.

Please help me overcome the issue.

Regards,
niranjan 

   line no-497                    

  lr_this_step = args.learning_rate * warmup_linear(global_step / num_train_optimization_steps,
                                                                          args.warmup_proportion)

**Comment by enod** [comment]
Hi there,

warmup_linear comes from [pytorch-pretrained-BERT](https://github.com/huggingface/pytorch-pretrained-BERT). Make sure you have installed the library first.

**Comment by niranjan8129** [comment]
Thank YOU for your prompt response. Yes, I installed  pytorch-pretrained-BERT but getting warmup_linear error while importing .

### 
**C:\ProgramData\Anaconda3\python.exe C:/Users/a760239/PycharmProjects/untitled/test1.py
Traceback (most recent call last):
  File "C:/Users/a760239/PycharmProjects/untitled/test1.py", line 16, in <module>
    **from pytorch_pretrained_bert.optimization import BertAdam, warmup_linear
ImportError: cannot import name 'warmup_linear' from 'pytorch_pretrained_bert.optimization'** (C:\ProgramData\Anaconda3\lib\site-packages\pytorch_pretrained_bert\optimization.py)

Process finished with exit code 1**

**Comment by enod** [comment]
They just released new version of the library. 

If you see this [line](https://github.com/huggingface/pytorch-transformers/blob/f31154cb9df44b9535bd21eb5962e7a91711e9d1/examples/lm_finetuning/simple_lm_finetuning.py#L35) you are able to see how it imports.
